name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: week1-practice-test
      id: week1-practice-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: week1-practice-test
        setup-command: gcc main.c -o main
        command: "./main"
        input: ''
        expected-output: ".*[hH]ello.*[wW]orld.*"
        comparison-method: regex
        timeout: 1
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        WEEK1-PRACTICE-TEST_RESULTS: "${{steps.week1-practice-test.outputs.result}}"
      with:
        runners: week1-practice-test
